# etf_database.py - Enhanced ETF Data with Names
"""
ETF Database - Enhanced with Names
Contains ETF ticker mappings, classifications, static descriptive fields, and names
All logic, patterns, constraints, and configuration moved to config.py
"""

class ETFDatabase:
    """
    Pure ETF data storage - no logic, no patterns, no constraints
    Just static ETF information
    """
    
    def __init__(self):
        # Pure data storage with names - just the facts about each ETF
        self.etf_data = {
            'XALG.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'MSCI World Net Return Index (AUD)', 'type': 'broad_market', 'name': 'Alphinity Global Equity - Active ETF (Managed Fund)'},
            'XASG.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'MSCI World Net Total Return Index (AUD)', 'type': 'broad_market', 'name': 'Alphinity Global Sustainable Equity Fund - Active ETF (Managed Fund)'},
            'AGX1.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'N/A', 'type': 'broad_market', 'name': 'BetaShares Asia Technology Tigers ETF'},
            'BAOR.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'MSCI All Countries World Index ex Australia Accumulation Index Net in AUD', 'type': 'broad_market', 'name': 'BetaShares Asia Technology Tigers ETF - Currency Hedged'},
            'DAOR.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'MSCI All Countries World Index ex Australia Accumulation Index Net in AUD (hedged)', 'type': 'broad_market', 'name': 'Aoris International Fund Class D Managed Fund Hedged'},
            'ADEF.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'MSCI All Country World Index (ex Australia) before fees', 'type': 'broad_market', 'name': 'Apostle Dundas Global Equity Fund - Class D Units Active ETF (Managed Fund)'},
            'GLOB.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'MSCI World Net Total Return Index (AUD)', 'type': 'broad_market', 'name': 'Barrow Hanley Global Share Active ETF'},
            'DZZF.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'N/A', 'type': 'broad_market', 'name': 'BetaShares Ethical Diversified High Growth ETF'},
            'DGGF.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'N/A', 'type': 'broad_market', 'name': 'BetaShares Ethical Diversified Growth ETF'},
            'DHHF.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'N/A', 'type': 'broad_market', 'name': 'BetaShares Diversified All Growth ETF'},
            'DBBF.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'N/A', 'type': 'broad_market', 'name': 'BetaShares Ethical Diversified Balanced ETF'},
            'HQLT.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'iSTOXX MUTB Global Ex-Australia Quality Leaders Index AUD Hedged', 'type': 'broad_market', 'name': 'Betashares Global Quality Leaders Currency Hedged ETF'},
            'QLTY.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'iSTOXX MUTB Global ex-Australia Quality Leaders', 'type': 'broad_market', 'name': 'BetaShares Global Quality Leaders ETF'},
            'BGBL.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'Solactive GBS Developed Markets ex Australia Large & Mid Cap Index', 'type': 'broad_market', 'name': 'Betashares Global Shares ETF Units AUD'},
            'HGBL.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'Solactive GBS Developed Markets ex Australia Large & Mid Cap Index (AUD Hedged)', 'type': 'broad_market', 'name': 'Betashares Global Shares Currency Hedged ETF'},
            'WRLD.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'N/A', 'type': 'broad_market', 'name': 'Betashares Managed Risk Global Shares Complex ETF'},
            'GHHF.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'N/A', 'type': 'broad_market', 'name': 'Betashares Wealth Builder Diversified All Growth Geared (30-40% LVR) Complex ETF'},
            'DHOF.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'RBA Cash Rate', 'type': 'bond', 'name': 'Daintree Hybrid Opportunities Fund (Managed Fund)'},
            'FCAP.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'MSCI World Mid Cap Index NR', 'type': 'broad_market', 'name': 'Fidelity Global Future Leaders Active ETF'},
            'S3GO.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'MSCI World Net Total Return Index (AUD)', 'type': 'broad_market', 'name': 'Firetrail S3 Global Opportunities Fund - Active ETF'},
            'FRGG.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'MSCI World ex Australia Index', 'type': 'broad_market', 'name': 'Franklin Global Growth Fund (A Class) ETF'},
            'ISLM.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'MSCI World Islamic Index (hedged into AUD)', 'type': 'broad_market', 'name': 'Hejaz Equities Fund (Managed Fund)'},
            'HYGG.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'MSCI World Accumulation', 'type': 'broad_market', 'name': 'Hyperion Global Growth Companies Fund-Active ETF'},
            'IISV.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'S&P/ASX 200 Accumulation Index', 'type': 'broad_market', 'name': 'Intelligent Investor Select Value Share Fd ETF'},
            'IBAL.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'N/A', 'type': 'broad_market', 'name': 'iShares Balanced ESG ETF'},
            'IWLD.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'MSCI World Investible Market', 'type': 'broad_market', 'name': 'iShares Core MSCI World Ex Australia ESG ETF'},
            'IHWL.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'MSCI World Investable Market', 'type': 'broad_market', 'name': 'iShares Core MSCI World ex Australia ESG (AUD Hedged) ETF'},
            'WVOL.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'MSCI World Minimum Volatility (AUD)', 'type': 'broad_market', 'name': 'iShares MSCI World ex Australia Minimum Volatility ETF'},
            'WDMF.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'MSCI World Diversified Multiple-Factor (AUD)', 'type': 'broad_market', 'name': 'iShares World Equity Factor ETF'},
            'IOO.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'S&P Global 100', 'type': 'broad_market', 'name': 'iShares Global 100 ETF (AU)'},
            'IHOO.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'S&P Global 100', 'type': 'broad_market', 'name': 'iShares Global 100 AUD Hedged ETF'},
            'IGRO.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'N/A', 'type': 'broad_market', 'name': 'iShares High Growth ESG ETF'},
            'IVE.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'MSCI EAFE Index', 'type': 'broad_market', 'name': 'iShares MSCI EAFE ETF (AU)'},
            'FUTR.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'MSCI World Index (net dividends reinvested) (AUD)', 'type': 'broad_market', 'name': 'Janus Henderson Global Sustainable Equity Active ETF'},
            'JREG.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'MSCI World ex Australia Index (Total Return Net)', 'type': 'broad_market', 'name': 'JPMorgan Global Research Enhanced Index Equity Active ETF'},
            'T3MP.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'MSCI All Country World Index (Total Return Net) - AUD', 'type': 'broad_market', 'name': 'JPMorgan Climate Change Solutions Active ETF'},
            'JEGA.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'MSCI World Index (Total Return Net)', 'type': 'broad_market', 'name': 'JPMorgan Global Equity Premium Income Complex ETF'},
            'JHGA.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'MSCI World Index (Total Return Net)', 'type': 'broad_market', 'name': 'JPMorgan Global Equity Premium Income (Hedged) Complex ETF'},
            'JRHG.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'MSCI World ex Australia Index', 'type': 'broad_market', 'name': 'JPMorgan Global Research Enhanced Index Equity (Hedged) Active ETF'},
            'JHLO.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'MSCI World Index (Net Total Return) hedged to AUD', 'type': 'broad_market', 'name': 'JPMorgan Global Select Equity (Hedged) Active ETF'},
            'JGLO.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'MSCI World Index (Net Total Return)', 'type': 'broad_market', 'name': 'JPMJGLO ETF UNITS [JGLO]'},
            'L1IF.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'MSCI World Net Total Return Index in AUD', 'type': 'broad_market', 'name': 'L1 Capital International ETF'},
            'LNYN.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'S&P/ASX 300 Accumulation Index and MSCI All Country World Index', 'type': 'broad_market', 'name': 'Lanyon Investment Fund Active ETF'},
            'LPGD.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'MSCI All Countries World', 'type': 'broad_market', 'name': 'Loftus Peak Global Disruption Fund (Managed Fund)'},
            'LSGE.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'MSCI All Country World Index', 'type': 'broad_market', 'name': 'Loomis Sayles Global Equity Quoted Managed Fund'},
            'MQEG.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'MSCI World ex-Australia ex-Tobacco Net Dividends Reinvested Index', 'type': 'broad_market', 'name': 'Macquarie Core Global Equity Active ETF'},
            'MQWS.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'MSCI World ex Australia Index', 'type': 'broad_market', 'name': 'Macquarie Walter Scott Global Equity Active ETF'},
            'MHG.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'MSCI World Net Total Return Index (hedged to AUD)', 'type': 'broad_market', 'name': 'Magellan Global Equities Fund (Currency Hedged'},
            'MGOC.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'MSCI World Net Total Return Index (AUD)', 'type': 'broad_market', 'name': 'Magellan Global Fund (Open Class) (Managed Fund)'},
            'MHHT.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'N/A', 'type': 'broad_market', 'name': 'MHHT.AX'},
            'MFOA.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'RBA Cash Rate + 5% pa', 'type': 'broad_market', 'name': 'Milford Australian Absolute Growth Fund Quoted Class Hedge Complex ETF'},
            'MKAX.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'N/A', 'type': 'broad_market', 'name': 'Montaka Global Extension Fund (Quoted Managed Hedge Fund)'},
            'MOGL.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'MSCI World Net Total Return Index', 'type': 'broad_market', 'name': 'Montaka Global Long Only Equities ETF (Managed Fund)'},
            'MAET.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'N/A', 'type': 'broad_market', 'name': 'Munro Global Growth Fund Complex ETF'},
            'NNUK.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'N/A', 'type': 'broad_market', 'name': 'Nanuk New World Fund'},
            'QYLD.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'US NASDAQ', 'type': 'dividend', 'name': 'Global X Nasdaq 100 Covered Call ETF'},
            'QNDQ.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'Nasdaq-100 Equal Weighted Index', 'type': 'broad_market', 'name': 'Betashares Nasdaq 100 Equal Weight ETF'},
            'JNDQ.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'Nasdaq Next Generation 100 Index', 'type': 'growth', 'name': 'Betashares Nasdaq Next Gen 100 ETF'},
            'PIXX.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'N/A', 'type': 'broad_market', 'name': 'Platinum International Fund (Quoted Managed Hedge Fund)'},
            'RGOS.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'MSCI ACWI – Net', 'type': 'broad_market', 'name': 'Russell Investments Sustainable Global Opportunities Complex ETF'},
            'GROW.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'N/A', 'type': 'broad_market', 'name': 'Schroder Real Return Active ETF'},
            'QMIX.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'MSIC World Quality Mix', 'type': 'broad_market', 'name': 'SPDR MSCI World Quality Mix ETF'},
            'HVLU.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'MSCI World ex Australia Enhanced Value Top 250 Select 100% Hedged to AUD Index', 'type': 'broad_market', 'name': 'VanEck MSCI International Value (AUD Hedged) ETF'},
            'VLUE.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'MSCI’s World ex Australia Enhanced Value Top 250 Select', 'type': 'broad_market', 'name': 'VanEck MSCI International Value ETF'},
            'GOAT.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'Morningstar® Developed Markets ex-Australia Wide Moat Focus', 'type': 'broad_market', 'name': 'VanEck Morningstar International Wide Moat ETF'},
            'VDBA.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'Balanced Composite Index', 'type': 'broad_market', 'name': 'Vanguard Diversified Balanced Index ETF'},
            'VDCO.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'Conservative Composite Index', 'type': 'broad_market', 'name': 'Vanguard Diversified Conservative Index ETF'},
            'VDGR.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'Growth Composite Index', 'type': 'broad_market', 'name': 'Vanguard Diversified Growth Index ETF'},
            'VDHG.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'High Growth Composite', 'type': 'broad_market', 'name': 'Vanguard Diversified High Growth Index ETF'},
            'VESG.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'FTSE Developed ex-Aus, ex Non-renewable, Vice Products & Weapons', 'type': 'broad_market', 'name': 'Vanguard Ethically Conscious International Shares Index ETF'},
            'VMIN.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'FTSE Global All Cap', 'type': 'broad_market', 'name': 'Vanguard Global Minimum Volatility Active ETF'},
            'VVLU.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'N/A', 'type': 'broad_market', 'name': 'Vanguard Global Value Equity Active ETF'},
            'VNGS.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'MSCI ACWI SMID Cap Index', 'type': 'growth', 'name': 'Vaughan Nelson Global Equity SMID Fund (Quoted Managed Fund)'},
            'WCMQ.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'MSCI All Country World Index ex-Australia', 'type': 'growth', 'name': 'WCM Quality Global Growth Fund-Active ETF'},
            'URNM.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'Indxx North Shore Uranium Mining Index', 'type': 'commodity', 'name': 'BetaShares Global Uranium ETF'},
            'ASIA.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'Solactive Asia Ex-Japan Technology & Internet Tigers', 'type': 'growth', 'name': 'BetaShares Asia Technology Tigers ETF'},
            'ERTH.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'Solactive Climate Change And Environmental Opportunities', 'type': 'sector', 'name': 'BetaShares Climate Change Innovation ETF'},
            'CLDD.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'Indxx Global Cloud Computing', 'type': 'sector', 'name': 'BetaShares Cloud Computing ETF'},
            'CRYP.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'Bitwise Crypto Innovators Index', 'type': 'crypto', 'name': 'BetaShares Crypto Innovators ETF'},
            'EDOC.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'N/A', 'type': 'sector', 'name': 'Betashares Digital Health And Telemedicine Etf'},
            'DRIV.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'Solactive Future Mobility Index', 'type': 'sector', 'name': 'BetaShares Electric Vhcl & Fut Mblty ETF'},
            'XMET.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'Nasdaq Sprott Energy Transition Materials Select Index', 'type': 'commodity', 'name': 'BetaShares Energy Transition Metals ETF'},
            'F100.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'FTSE 100', 'type': 'broad_market', 'name': 'BetaShares FTSE 100 ETF'},
            'IEAT.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'Foxberry Next Generation Foods Index', 'type': 'sector', 'name': 'BetaShares Future of Food ETF'},
            'IPAY.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'Nasdaq CTA Global Digital Payments Index', 'type': 'sector', 'name': 'Betashares Future Of Payments Etf'},
            'HACK.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'Nasdaq Consumer Technology Association Cybersecurity', 'type': 'sector', 'name': 'BetaShares Global Cybersecurity ETF'},
            'FUEL.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'Nasdaq Global ex-Australia Energy (Hedged AUD)', 'type': 'commodity', 'name': 'Betashares Global Energy Companies Currency Hedged ETF'},
            'DRUG.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'Nasdaq Global ex-Australia Healthcare (Hedged AUD)', 'type': 'sector', 'name': 'Betashares Global Healthcare Currency Hedged ETF'},
            'RBTZ.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'Indxx Global Robotics & Artificial Intelligence Thematic', 'type': 'growth', 'name': 'BetaShares Global Robotics and Artificial Intelligence ETF'},
            'ROYL.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'Solactive Global Royalties Index', 'type': 'sector', 'name': 'BetaShares Global Royalties ETF'},
            'ETHI.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'Nasdaq Future Global Sustainability Leaders', 'type': 'sector', 'name': 'BetaShares Global Sustainability Leaders ETF'},
            'HETH.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'NASDAQ Future Global Sustainability Leaders Currency Hedged AUD', 'type': 'sector', 'name': 'Betashares Global Sustainability Leaders Currency Hedged ETF'},
            'BNKS.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'NASDAQ Global ex-Australia Banks Hedged AUD', 'type': 'sector', 'name': 'Betashares Global Banks Currency Hedged ETF'},
            'MTAV.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'Bloomberg Metaverse Select Index', 'type': 'growth', 'name': 'Betashares Metaverse Etf'},
            'IBUY.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'Solactive Global Online Retail and E-Commerce Index', 'type': 'sector', 'name': 'Betashares Online Retail And E-Commerce ETF'},
            'TANN.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'Solactive EQM Global Solar Energy Index', 'type': 'sector', 'name': 'Betashares Solar Etf'},
            'GAME.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'Nasdaq CTA Global Video Games & Esports Index', 'type': 'sector', 'name': 'BetaShares Video Games and Esports ETF'},
            'FANG.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'NYSE®FANG+™', 'type': 'growth', 'name': 'Global X FANG+ ETF'},
            'TECH.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'Morningstar® Developed Markets Technology Moat Focus', 'type': 'sector', 'name': 'Global X Morningstar Global Technology ETF'},
            'HGEN.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'Solactive Global Hydrogen ESG Index', 'type': 'sector', 'name': 'Global X Hydrogen ETF'},
            'CURE.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'S&P Biotechnology Select Industry Index', 'type': 'sector', 'name': 'Global X S&P Biotech ETF'},
            'SEMI.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'Solactive Global Semiconductor 30 Index', 'type': 'sector', 'name': 'Global X Semiconductor ETF'},
            'WIRE.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'Solactive Global Copper Miners Total Return Index', 'type': 'commodity', 'name': 'Global X Copper Miners ETF AUD Inc'},
            'BUGG.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'Indxx Cybersecurity Index', 'type': 'sector', 'name': 'Global X Cybersecurity ETF'},
            'GCO2.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'ICE Global Carbon Futures Index (AUD Total Return)', 'type': 'sector', 'name': 'Global X Global Carbon ETF (Synthetic)'},
            'GMTL.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'BITA Global Green Energy Metals Index', 'type': 'commodity', 'name': 'Global X Green Metal Miners ETF'},
            'ATOM.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'Solactive Global Uranium & Nuclear Components Total Return Index', 'type': 'commodity', 'name': 'Global X Uranium ETF'},
            'HHIF.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'MSCI ACWI IMI Innovation (hedged to AUD)', 'type': 'growth', 'name': 'HEJAZ High Innovation Active ETF'},
            'GLIN.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'FTSE Developed Core Infrastructure 50/50 100% Hedged to AUD Net Tax Index', 'type': 'sector', 'name': 'iShares Core FTSE Global Infrastructure (AUD Hedged) ETF'},
            'GLPR.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'FTSE EPRA Nareit Developed ex-Australia Rental AUD Hedged Net Tax Index', 'type': 'sector', 'name': 'iShares Core FTSE Global Property Ex Australia (AUD Hedged) ETF'},
            'ITEK.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'N/A', 'type': 'growth', 'name': 'iShares Nasdaq Top 30 ETF'},
            'IXI.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'S&P Global Consumer Staples', 'type': 'sector', 'name': 'iShares Global Consumer Staples ETF (AU)'},
            'IXJ.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'S&P Global Healthcare', 'type': 'sector', 'name': 'iShares Global Healthcare ETF (AU)'},
            'JPSI.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'MSCI All Country World Index (Total Return Net) - AUD', 'type': 'sector', 'name': 'Jpmorgan Asset Management (Australia) Ltd. - Sustainable Infrastructure Active ETF'},
            'MICH.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'S&P Global Infrastructure Index A$ Hedged Net Total Return', 'type': 'sector', 'name': 'Magellan Infrastructure Fund (Currency Hedged)'},
            'MCCL.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'N/A', 'type': 'sector', 'name': 'Munro Climate Change Leaders Fund Active ETF'},
            'JZRO.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'N/A', 'type': 'sector', 'name': 'Janus Henderson Net Zero Transition Resources Active ETF'},
            'RCAP.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'FTSE EPRA/NAREIT Developed Index (AUD Hedged) Net TRI', 'type': 'sector', 'name': 'Resolution Capital Global Property Securities - Active ETF'},
            'DJRE.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'Dow Jones Global Select Real Estate Securities', 'type': 'sector', 'name': 'SPDR Dow Jones Global Real Estate ESG Tilted ETF'},
            'VBTC.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'MarketVector™ Bitcoin Benchmark Rate', 'type': 'crypto', 'name': 'VanEck Bitcoin ETF'},
            'CLNE.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'S&P Global Clean Energy Select', 'type': 'sector', 'name': 'VanEck Global Clean Energy ETF'},
            'XCO2.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'ICE Global Carbon Futures AUD', 'type': 'sector', 'name': 'Vaneck Global Carbon Credits Etf (Synthetic)'},
            'LEND.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'LPX Listed Private Credit AUD Hedged Index', 'type': 'sector', 'name': 'VanEck Global Listed Private Credit (AUD Hedged) ETF'},
            'GPEQ.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'LPX50 Index', 'type': 'sector', 'name': 'VanEck Global Listed Private Equity ETF'},
            'QHSM.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'MSCI World ex Australia Small Cap Quality 150 100% Hedged to AUD Index', 'type': 'growth', 'name': 'VanEck MSCI International Small Companies Quality (AUD Hedged) ETF'},
            'CNEW.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'CSI MarketGrader China New Economy', 'type': 'growth', 'name': 'VanEck China New Economy ETF'},
            'GXAI.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'CSI MarketGrader China New Economy', 'type': 'growth', 'name': 'Global X Artificial Intelligence ETF'},
            'IFRA.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'FTSE Developed Core Infrastructure 50/50 (Hedged AUD)', 'type': 'sector', 'name': 'VanEck FTSE Global Infrastructure (AUD Hedged) ETF'},
            'REIT.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'FTSE EPRA Nareit Developed ex Australia Rental Index AUD Hedged', 'type': 'sector', 'name': 'VanEck FTSE International Property (AUD Hedged) ETF'},
            'HLTH.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'MarketGrader Developed Markets (ex-Australia) Health Care', 'type': 'sector', 'name': 'VanEck Global Healthcare Leaders ETF'},
            'QSML.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'MSCI World ex Australia Small Cap Quality 150', 'type': 'growth', 'name': 'VanEck MSCI International Small Companies Quality ETF'},
            'ESGI.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'MSCI World ex-Australia (with filters)', 'type': 'sector', 'name': 'VanEck MSCI International Sustainable Equity ETF'},
            'ESPO.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'MVIS Global Video Gaming and eSports', 'type': 'sector', 'name': 'VanEck Video Gaming and eSports ETF'},
            'VBLD.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'FTSE Developed Core Infrastructure Index (with net dividends reinvested) AUD', 'type': 'sector', 'name': 'Vanguard Global Infrastructure Index ETF'},
            'VISM.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'MSCI World ex-Australia Small Cap Index (net dividends reinvested)', 'type': 'growth', 'name': 'Vanguard MSCI International Small Companies Index ETF'},
            'INCM.AX': {'region': 'GLOBAL', 'subcategory': 'Yield', 'benchmark': 'NASDAQ Global Income Leaders NTR', 'type': 'dividend', 'name': 'Betashares S&P Global High Dividend Aristocrats ETF'},
            'HJHI.AX': {'region': 'GLOBAL', 'subcategory': 'Yield', 'benchmark': 'DJI Islamic Market Global Select Dividend Index', 'type': 'dividend', 'name': 'HEJAZ High Income Active ETF'},
            'WDIV.AX': {'region': 'GLOBAL', 'subcategory': 'Yield', 'benchmark': 'S&P Global Dividend Aristocrats', 'type': 'dividend', 'name': 'SPDR S&P Global Dividend ETF'},
            'VEU.AX': {'region': 'GLOBAL', 'subcategory': 'Ex-US / Canada', 'benchmark': 'FTSE All World Ex-US', 'type': 'broad_market', 'name': 'Vanguard MSCI Index International Shares ETF'},
            'CGUN.AX': {'region': 'GLOBAL', 'subcategory': 'Ex-Australia', 'benchmark': 'MSCI AC World Accum Index ex-Aust', 'type': 'broad_market', 'name': 'Claremont Global Fund (Managed Fund)'},
            'CGHE.AX': {'region': 'GLOBAL', 'subcategory': 'Ex-Australia', 'benchmark': 'MSCI AC World Accum Index ex-Aust', 'type': 'broad_market', 'name': 'Claremont Global Fund (hedged) (Managed Fund)'},
            'DFGH.AX': {'region': 'GLOBAL', 'subcategory': 'Ex-Australia', 'benchmark': 'MSCI World ex Australia Index (net div.)', 'type': 'broad_market', 'name': 'Dimensional Global Core Equity Hedged Active ETF'},
            'DGCE.AX': {'region': 'GLOBAL', 'subcategory': 'Ex-Australia', 'benchmark': 'MSCI World ex Australia Index (net div.)', 'type': 'broad_market', 'name': 'Dimensional Global Core Equity Trust (Unhedged Class) - Active ETF'},
            'MSTR.AX': {'region': 'GLOBAL', 'subcategory': 'Ex-Australia', 'benchmark': 'MSCI All Country World ex-Australia Index with Net Dividends Reinvested', 'type': 'broad_market', 'name': 'Morningstar International Shares Active ETF (Managed Fund)'},
            'MCGG.AX': {'region': 'GLOBAL', 'subcategory': 'Ex-Australia', 'benchmark': 'MSCI World (Ex-Australia) Index', 'type': 'growth', 'name': 'Munro Concentrated Global Growth Fund Active ETF'},
            'WXHG.AX': {'region': 'GLOBAL', 'subcategory': 'Ex-Australia', 'benchmark': 'S&P Developed ex-Australia LargeMidCap (Hedged AUD)', 'type': 'broad_market', 'name': 'SPDR S&P World ex Australia Carbon Aware (Hedged) ETF'},
            'WXOZ.AX': {'region': 'GLOBAL', 'subcategory': 'Ex-Australia', 'benchmark': 'S&P Developed ex-Australia LargeMidCap AUD', 'type': 'broad_market', 'name': 'SPDR S&P World ex Australia Carbon Aware ETF'},
            'QUAL.AX': {'region': 'GLOBAL', 'subcategory': 'Ex-Australia', 'benchmark': 'MSCI World ex-Australia Quality', 'type': 'broad_market', 'name': 'Vaneck Msci International Quality Etf'},
            'QHAL.AX': {'region': 'GLOBAL', 'subcategory': 'Ex-Australia', 'benchmark': 'MSCI World ex-Australia Quality', 'type': 'broad_market', 'name': 'VanEck MSCI International Quality (AUD Hedged) ETF'},
            'VGS.AX': {'region': 'GLOBAL', 'subcategory': 'Ex-Australia', 'benchmark': 'MSCI World ex-Australia', 'type': 'broad_market', 'name': 'Vanguard MSCI Index International Shares ETF'},
            'VGAD.AX': {'region': 'GLOBAL', 'subcategory': 'Ex-Australia', 'benchmark': 'MSCI World ex-Australia (Hedged AUD)', 'type': 'broad_market', 'name': 'Vanguard MSCI Index International Shares (Hedged) ETF'},
            'EMMG.AX': {'region': 'GLOBAL', 'subcategory': 'Emerging Markets', 'benchmark': 'N/A', 'type': 'broad_market', 'name': 'Betashares Legg Mason Emerging Markets Fund Managed Fund'},
            'FEMX.AX': {'region': 'GLOBAL', 'subcategory': 'Emerging Markets', 'benchmark': 'N/A', 'type': 'broad_market', 'name': 'Fidelity Global Emerging Markets ETF'},
            'IHEB.AX': {'region': 'GLOBAL', 'subcategory': 'Emerging Markets', 'benchmark': 'J.P. Morgan EMBI Global Core Index (AUD Hedged)', 'type': 'bond', 'name': 'iShares JP Morgan USD Emerging Markets Bond (AUD Hedged) ETF'},
            'IEM.AX': {'region': 'GLOBAL', 'subcategory': 'Emerging Markets', 'benchmark': 'MSCI Emerging Markets Index', 'type': 'broad_market', 'name': 'iShares MSCI Emerging Markets ETF (AU)'},
            'EMXC.AX': {'region': 'GLOBAL', 'subcategory': 'Emerging Markets', 'benchmark': 'MSCI Emerging Markets ex China Index', 'type': 'broad_market', 'name': 'iShares MSCI Emerging Markets ex China ETF'},
            'WEMG.AX': {'region': 'GLOBAL', 'subcategory': 'Emerging Markets', 'benchmark': 'S&P Emerging Markets LargeMidCaps', 'type': 'broad_market', 'name': 'SPDR S&P Emerging Markets Carbon Aware ETF'},
            'EBND.AX': {'region': 'GLOBAL', 'subcategory': 'Emerging Markets', 'benchmark': 'N/A', 'type': 'bond', 'name': 'VanEck Emerging Income Opportunities Active ETF (Managed Fund)'},
            'EMKT.AX': {'region': 'GLOBAL', 'subcategory': 'Emerging Markets', 'benchmark': 'MSCI Emerging Markets', 'type': 'broad_market', 'name': 'VanEck MSCI Multifactor Emerging Markets Equity ETF'},
            'VGE.AX': {'region': 'GLOBAL', 'subcategory': 'Emerging Markets', 'benchmark': 'FTSE Emerging Markets All Cap China A Inclusion', 'type': 'broad_market', 'name': 'Vanguard FTSE Emerging Markets Shares ETF'},
            'US10.AX': {'region': 'GLOBAL', 'subcategory': 'Fixed Interest', 'benchmark': 'Bloomberg U.S. Treasury: 7-10 Year Total Return Index Hedged AUD', 'type': 'bond', 'name': 'Betashares U.S. Treasury Bond 7-10 Year Currency Hedged ETF'},
            'VCF.AX': {'region': 'GLOBAL', 'subcategory': 'Fixed Interest', 'benchmark': 'Bloomberg Barclays Global Aggregate Government-related and Corporate', 'type': 'bond', 'name': 'Vanguard International Credit Securities Index (Hedged) ETF'},
            'VIF.AX': {'region': 'GLOBAL', 'subcategory': 'Fixed Interest', 'benchmark': 'Bloomberg Barclays Global Treasury Index (AUD Hedged)', 'type': 'bond', 'name': 'Vanguard International Fixed Interest Index (Hedged) ETF'},
            'POU.AX': {'region': 'GLOBAL', 'subcategory': 'Cash / Bonds / Currencies', 'benchmark': 'British Pound', 'type': 'bond', 'name': 'BetaShares British Pound ETF'},
            'EEU.AX': {'region': 'GLOBAL', 'subcategory': 'Cash / Bonds / Currencies', 'benchmark': 'Euro', 'type': 'bond', 'name': 'BetaShares Euro ETF'},
            'CFLO.AX': {'region': 'GLOBAL', 'subcategory': 'Cash / Bonds / Currencies', 'benchmark': 'Solactive Global ex-Australia Cash Flow Kings Index', 'type': 'dividend', 'name': 'Betashares Global Cash Flow Kings ETF'},
            'GGOV.AX': {'region': 'GLOBAL', 'subcategory': 'Cash / Bonds / Currencies', 'benchmark': 'S&P G7 Sovereign Duration-Capped 20+ Year AUD Hedged Bond', 'type': 'bond', 'name': 'Betashares US Treasury Bond 20+ Year Currency Hedged ETF'},
            'YANK.AX': {'region': 'GLOBAL', 'subcategory': 'Cash / Bonds / Currencies', 'benchmark': 'US Dollar', 'type': 'bond', 'name': 'Betashares Strong US Dollar Complex ETF'},
            'GBND.AX': {'region': 'GLOBAL', 'subcategory': 'Cash / Bonds / Currencies', 'benchmark': 'Solactive Australian and Global Select Sustainability Leaders Bond TR Index - AUD Hedged', 'type': 'bond', 'name': 'Betashares Global Green Bond Currency Hedged ETF'},
            'USD.AX': {'region': 'GLOBAL', 'subcategory': 'Cash / Bonds / Currencies', 'benchmark': 'US Dollar', 'type': 'bond', 'name': 'BetaShares U.S. Dollar ETF'},
            'USTB.AX': {'region': 'GLOBAL', 'subcategory': 'Cash / Bonds / Currencies', 'benchmark': 'iBoxx $ Treasuries Index (AUD Hedged)', 'type': 'bond', 'name': 'Global X US Treasury Bond (Currency Hedged) ETF'},
            'USHY.AX': {'region': 'GLOBAL', 'subcategory': 'Cash / Bonds / Currencies', 'benchmark': 'Solactive USD High Yield Corporates Total Market Hedged to AUD Index', 'type': 'bond', 'name': 'Global X USD High Yield Bond (Currency Hedged) ETF'},
            'FRAR.AX': {'region': 'GLOBAL', 'subcategory': 'Cash / Bonds / Currencies', 'benchmark': 'Bloomberg AusBond Bank Bill Index', 'type': 'bond', 'name': 'Franklin Australian Absolute Return Bd A ETF'},
            'BBFD.AX': {'region': 'GLOBAL', 'subcategory': 'Cash / Bonds / Currencies', 'benchmark': 'N/A', 'type': 'bear', 'name': 'Betashares Geared Short US Treasury Bond Currency Hedged Complex ETF'},
            'USIG.AX': {'region': 'GLOBAL', 'subcategory': 'Cash / Bonds / Currencies', 'benchmark': 'Global X USD Corporate Bond ETF (Currency Hedged)', 'type': 'bond', 'name': 'Global X USD Corporate Bond (Currency Hedged) ETF'},
            'SKUK.AX': {'region': 'GLOBAL', 'subcategory': 'Cash / Bonds / Currencies', 'benchmark': 'Bloomberg Global Aggregate USD Sukuk Index', 'type': 'bond', 'name': 'Hejaz Sukuk Active ETF Class A'},
            'IHCB.AX': {'region': 'GLOBAL', 'subcategory': 'Cash / Bonds / Currencies', 'benchmark': 'Barclays Global Aggregate Corporate Bond', 'type': 'bond', 'name': 'iShares Core Global Corporate Bond (AUD Hedged) ETF'},
            'AESG.AX': {'region': 'GLOBAL', 'subcategory': 'Cash / Bonds / Currencies', 'benchmark': 'Bloomberg MSCI Global Aggregate Sustainable Green Bond SRI AUD Hedged Index', 'type': 'bond', 'name': 'iShares Global Aggregate Bond ESG (AUD Hedged) ETF'},
            'IHHY.AX': {'region': 'GLOBAL', 'subcategory': 'Cash / Bonds / Currencies', 'benchmark': 'Markit iBoxx Global Developed Markets Liquid High Yield Capped', 'type': 'bond', 'name': 'iShares Global High Yield Bond (AUD Hedged) ETF'},
            'GOOD.AX': {'region': 'GLOBAL', 'subcategory': 'Cash / Bonds / Currencies', 'benchmark': 'Bloomberg AusBond Composite 0-5 Yr Index', 'type': 'bond', 'name': 'Janus Henderson Sustainable Credit Active ETF'},
            'MQDB.AX': {'region': 'GLOBAL', 'subcategory': 'Cash / Bonds / Currencies', 'benchmark': 'Bloomberg Global Aggregate Index', 'type': 'bond', 'name': 'Macquarie Dynamic Bond Active ETF'},
            'GCAP.AX': {'region': 'GLOBAL', 'subcategory': 'Cash / Bonds / Currencies', 'benchmark': 'RBA Cash Rate + 3% per annum', 'type': 'bond', 'name': 'VanEck Bentham Global Capital Securities Active ETF (Managed Fund)'},
            'VEFI.AX': {'region': 'GLOBAL', 'subcategory': 'Cash / Bonds / Currencies', 'benchmark': 'Bloomberg Barclays Global Aggregate Float Adjusted Bond (Hedged)', 'type': 'bond', 'name': 'Vanguard Ethically Conscious Global Aggregate Bond Index (Hedged) ETF'},
            'VBND.AX': {'region': 'GLOBAL', 'subcategory': 'Cash / Bonds / Currencies', 'benchmark': 'Bloomberg Barclays Global Aggregate Float Adjusted Bond (AUD Adj)', 'type': 'bond', 'name': 'Vanguard Global Aggregate Bond (Hedged) Index ETF'},
            'AASF.AX': {'region': 'AUSTRALIA', 'subcategory': 'Broad Exposure', 'benchmark': 'S&P/ASX 200 Accumulation Index', 'type': 'broad_market', 'name': 'Airlie Australian Share Fund ETF'},
            'EX20.AX': {'region': 'AUSTRALIA', 'subcategory': 'Broad Exposure', 'benchmark': 'Nasdaq Australia Completion Cap', 'type': 'broad_market', 'name': 'BetaShares Australian Ex-20 Portfolio Diversifier ETF'},
            'AQLT.AX': {'region': 'AUSTRALIA', 'subcategory': 'Broad Exposure', 'benchmark': 'N/A', 'type': 'broad_market', 'name': 'BetaShares Australian Quality ETF'},
            'AUST.AX': {'region': 'AUSTRALIA', 'subcategory': 'Broad Exposure', 'benchmark': 'N/A', 'type': 'broad_market', 'name': 'Betashares Managed Risk Australian Shares Complex ETF'},
            'G200.AX': {'region': 'AUSTRALIA', 'subcategory': 'Broad Exposure', 'benchmark': 'N/A', 'type': 'broad_market', 'name': 'Betashares Wealth Builder Australia 200 Geared (30-40% LVR) Complex ETF'},
            'DACE.AX': {'region': 'AUSTRALIA', 'subcategory': 'Broad Exposure', 'benchmark': 'S&P/ASX 300 Index (Total Return)', 'type': 'broad_market', 'name': 'Dimensional Australia Core Equity Trust - Active ETF'},
            'BBAB.AX': {'region': 'AUSTRALIA', 'subcategory': 'Broad Exposure', 'benchmark': 'N/A', 'type': 'bear', 'name': 'Betashares Geared Short Australian Government Bond Complex ETF'},
            'IIGF.AX': {'region': 'AUSTRALIA', 'subcategory': 'Broad Exposure', 'benchmark': 'S&P/ASX 200 Accumulation Index', 'type': 'broad_market', 'name': 'Intelligent Investor Australian Equity Growth Fund (Managed Fund)'},
            'MVOL.AX': {'region': 'AUSTRALIA', 'subcategory': 'Broad Exposure', 'benchmark': 'Subset of MSCI Australia IMI (AUD)', 'type': 'broad_market', 'name': 'iShares Edge MSCI Australia Minimum Volatility ETF'},
            'AUMF.AX': {'region': 'AUSTRALIA', 'subcategory': 'Broad Exposure', 'benchmark': 'Subset of MSCI Australia IMI (AUD)', 'type': 'broad_market', 'name': 'iShares Edge MSCI Australia Multifactor ETF'},
            'MAAT.AX': {'region': 'AUSTRALIA', 'subcategory': 'Broad Exposure', 'benchmark': 'Does not track a benchmark', 'type': 'broad_market', 'name': 'Monash Absolute Active Trust'},
            'GIVE.AX': {'region': 'AUSTRALIA', 'subcategory': 'Broad Exposure', 'benchmark': 'S&P/ASX 300 Accumulation Index', 'type': 'broad_market', 'name': 'Perpetual ESG Australian Share Active ETF'},
            'SWTZ.AX': {'region': 'AUSTRALIA', 'subcategory': 'Broad Exposure', 'benchmark': 'N/A', 'type': 'dividend', 'name': 'Switzer Dividend Growth Fund-Active ETF'},
            'GMVW.AX': {'region': 'AUSTRALIA', 'subcategory': 'Broad Exposure', 'benchmark': 'VanEck Australian Equal Weight ETF', 'type': 'broad_market', 'name': 'VanEck Geared Australian Equal Weight Fund (Hedge Fund)'},
            'MVW.AX': {'region': 'AUSTRALIA', 'subcategory': 'Broad Exposure', 'benchmark': 'MVIS Australia Equal Weight', 'type': 'broad_market', 'name': 'VanEck Australian Equal Weight ETF'},
            'VLC.AX': {'region': 'AUSTRALIA', 'subcategory': 'Broad Exposure', 'benchmark': 'MSCI Australian Shares Large Cap', 'type': 'broad_market', 'name': 'Vanguard MSCI Australian Large Companies Index ETF'},
            'BHYB.AX': {'region': 'AUSTRALIA', 'subcategory': 'Sectors', 'benchmark': 'Solactive Australian Banking Preferred Shared Index', 'type': 'sector', 'name': 'Betashares Australian Major Bank Hybrids Index ETF'},
            'FAIR.AX': {'region': 'AUSTRALIA', 'subcategory': 'Sectors', 'benchmark': 'Nasdaq Future Australian Sustainability Leaders', 'type': 'sector', 'name': 'BetaShares Australian Sustainability Leaders ETF'},
            'QFN.AX': {'region': 'AUSTRALIA', 'subcategory': 'Sectors', 'benchmark': 'S&P/ASX 200 Financials', 'type': 'sector', 'name': 'BetaShares Australian Financials Sector ETF'},
            'QRE.AX': {'region': 'AUSTRALIA', 'subcategory': 'Sectors', 'benchmark': 'S&P/ASX 200 Resources', 'type': 'sector', 'name': 'BetaShares Australian Resources Sector ETF'},
            'ACDC.AX': {'region': 'AUSTRALIA', 'subcategory': 'Sectors', 'benchmark': 'Solactive Battery Value-Chain', 'type': 'sector', 'name': 'Global X Battery Tech & Lithium ETF'},
            'ROBO.AX': {'region': 'AUSTRALIA', 'subcategory': 'Sectors', 'benchmark': 'ROBO Global Robotics and Automation', 'type': 'growth', 'name': 'Global X ROBO Global Robotics & Automation ETF'},
            'OZXX.AX': {'region': 'AUSTRALIA', 'subcategory': 'Sectors', 'benchmark': 'Solactive Australia ex Financials, Materials and Energy Capped Index', 'type': 'sector', 'name': 'Global X Australia Ex Financials & Resources ETF'},
            'INES.AX': {'region': 'AUSTRALIA', 'subcategory': 'Sectors', 'benchmark': 'N/A', 'type': 'sector', 'name': 'Intelligent Investor Ethical Share ETF'},
            'IESG.AX': {'region': 'AUSTRALIA', 'subcategory': 'Sectors', 'benchmark': 'MSCI Australia IMI Custom ESG Leaders', 'type': 'sector', 'name': 'iShares Core MSCI Australia ESG ETF'},
            'OZF.AX': {'region': 'AUSTRALIA', 'subcategory': 'Sectors', 'benchmark': 'S&P/ASX 200 Financials Ex-A-REIT', 'type': 'sector', 'name': 'SPDR S&P/ASX 200 Financials EX A-REIT ETF'},
            'SLF.AX': {'region': 'AUSTRALIA', 'subcategory': 'Sectors', 'benchmark': 'S&P/ASX 200 A-REIT', 'type': 'sector', 'name': 'SPDR S&P/ASX 200 Listed Property ETF'},
            'OZR.AX': {'region': 'AUSTRALIA', 'subcategory': 'Sectors', 'benchmark': 'S&P/ASX 200 Resources', 'type': 'sector', 'name': 'SPDR S&P/ASX 200 Resources ETF'},
            'MVB.AX': {'region': 'AUSTRALIA', 'subcategory': 'Sectors', 'benchmark': 'MVIS Australia Banks', 'type': 'sector', 'name': 'VanEck Australian Banks ETF'},
            'MVR.AX': {'region': 'AUSTRALIA', 'subcategory': 'Sectors', 'benchmark': 'MVIS Australia Energy & Mining', 'type': 'sector', 'name': 'VanEck Australian Resources ETF'},
            'GRNV.AX': {'region': 'AUSTRALIA', 'subcategory': 'Sectors', 'benchmark': 'MSCI Australia IMI Select SRI Screened', 'type': 'sector', 'name': 'VanEck MSCI Australian Sustainable Equity ETF'},
            'MVE.AX': {'region': 'AUSTRALIA', 'subcategory': 'Sectors', 'benchmark': 'S&P/ASX Midcap 50', 'type': 'sector', 'name': 'VanEck S&P/ASX MidCap ETF'},
            'VETH.AX': {'region': 'AUSTRALIA', 'subcategory': 'Sectors', 'benchmark': 'FTSE Australia 300 Choice Index', 'type': 'sector', 'name': 'Vanguard Ethically Conscious Australian Shares ETF'},
            'MTUM.AX': {'region': 'AUSTRALIA', 'subcategory': 'Index Tracking', 'benchmark': 'Solactive Australia Momentum Select Index', 'type': 'broad_market', 'name': 'Betashares Australian Momentum ETF'},
            'A200.AX': {'region': 'AUSTRALIA', 'subcategory': 'Index Tracking', 'benchmark': 'S&P/ASX 200', 'type': 'broad_market', 'name': 'BetaShares Australia 200 ETF'},
            'SMLL.AX': {'region': 'AUSTRALIA', 'subcategory': 'Index Tracking', 'benchmark': 'S&P/ASX Small Ordinaries Accumulation', 'type': 'growth', 'name': 'BetaShares Australian Small Companies Select ETF'},
            'QOZ.AX': {'region': 'AUSTRALIA', 'subcategory': 'Index Tracking', 'benchmark': 'FTSE RAFI Australia 200', 'type': 'broad_market', 'name': 'BetaShares FTSE RAFI Australia 200 ETF'},
            'GEAR.AX': {'region': 'AUSTRALIA', 'subcategory': 'Index Tracking', 'benchmark': 'S&P/ASX 200', 'type': 'broad_market', 'name': 'Betashares Geared Australian Equities Complex ETF'},
            'ATEC.AX': {'region': 'AUSTRALIA', 'subcategory': 'Index Tracking', 'benchmark': 'S&P/ASX All Technology', 'type': 'growth', 'name': 'BetaShares S&P/ASX Australian Technology ETF'},
            'FHCO.AX': {'region': 'AUSTRALIA', 'subcategory': 'Index Tracking', 'benchmark': 'S&P/ASX 200 Accumulation Index', 'type': 'broad_market', 'name': 'Fidelity Australian High Convct Act ETF'},
            'IOZ.AX': {'region': 'AUSTRALIA', 'subcategory': 'Index Tracking', 'benchmark': 'S&P/ASX 200', 'type': 'broad_market', 'name': 'iShares Core S&P/ASX 200 ETF'},
            'ILC.AX': {'region': 'AUSTRALIA', 'subcategory': 'Index Tracking', 'benchmark': 'S&P/ASX 20', 'type': 'broad_market', 'name': 'iShares S&P/ASX 20 ETF'},
            'MQAE.AX': {'region': 'AUSTRALIA', 'subcategory': 'Index Tracking', 'benchmark': 'S&P/ASX 300 Accumulation Index', 'type': 'broad_market', 'name': 'Macquarie Core Australian Equity Active ETF'},
            'STW.AX': {'region': 'AUSTRALIA', 'subcategory': 'Index Tracking', 'benchmark': 'S&P/ASX 200', 'type': 'broad_market', 'name': 'SPDR S&P/ASX 200 ETF'},
            'E200.AX': {'region': 'AUSTRALIA', 'subcategory': 'Index Tracking', 'benchmark': 'S&P/ASX 200 ESG', 'type': 'broad_market', 'name': 'SPDR S&P/ASX 200 ESG ETF'},
            'SFY.AX': {'region': 'AUSTRALIA', 'subcategory': 'Index Tracking', 'benchmark': 'S&P/ASX 50', 'type': 'broad_market', 'name': 'SPDR S&P/ASX 50 ETF'},
            'VAS.AX': {'region': 'AUSTRALIA', 'subcategory': 'Index Tracking', 'benchmark': 'S&P/ASX 300', 'type': 'broad_market', 'name': 'Vanguard Australian Shares Index ETF'},
            'IMPQ.AX': {'region': 'AUSTRALIA', 'subcategory': 'Small Cap', 'benchmark': 'N/A', 'type': 'growth', 'name': 'Perennial Better Future Fund'},
            'ISO.AX': {'region': 'AUSTRALIA', 'subcategory': 'Small Cap', 'benchmark': 'S&P/ASX Small Ordinaries', 'type': 'growth', 'name': 'iShares S&P/ASX Small Ordinaries ETF'},
            'KSM.AX': {'region': 'AUSTRALIA', 'subcategory': 'Small Cap', 'benchmark': 'N/A', 'type': 'growth', 'name': 'K2 Australian Small Cap Fund'},
            'SSO.AX': {'region': 'AUSTRALIA', 'subcategory': 'Small Cap', 'benchmark': 'S&P/ASX Small Ordinaries', 'type': 'growth', 'name': 'SPDR S&P/ASX Small Ordinaries ETF'},
            'MVS.AX': {'region': 'AUSTRALIA', 'subcategory': 'Small Cap', 'benchmark': 'MVIS Australia Small-Cap Dividend Payers', 'type': 'growth', 'name': 'VanEck Small Companies Masters ETF'},
            'VSO.AX': {'region': 'AUSTRALIA', 'subcategory': 'Small Cap', 'benchmark': 'MSCI Australian Shares Small Cap', 'type': 'growth', 'name': 'Vanguard MSCI Australian Small Companies Index ETF'},
            'HBRD.AX': {'region': 'AUSTRALIA', 'subcategory': 'Yield', 'benchmark': 'N/A', 'type': 'dividend', 'name': 'Betashares Australian Hybrids Active ETF'},
            'HVST.AX': {'region': 'AUSTRALIA', 'subcategory': 'Yield', 'benchmark': 'N/A', 'type': 'dividend', 'name': 'Betashares Australian Dividend Harvester Active ETF'},
            'YMAX.AX': {'region': 'AUSTRALIA', 'subcategory': 'Yield', 'benchmark': 'S&P/ASX 20', 'type': 'dividend', 'name': 'Betashares Australian Top 20 Equities Yield Maximiser Complex ETF'},
            'EINC.AX': {'region': 'AUSTRALIA', 'subcategory': 'Yield', 'benchmark': 'N/A', 'type': 'dividend', 'name': 'Betashares Capital Ltd. -  Legg Mason Equity Income (Managed) Fund'},
            'RINC.AX': {'region': 'AUSTRALIA', 'subcategory': 'Yield', 'benchmark': 'N/A', 'type': 'dividend', 'name': 'BetaShares Legg Mason Real Income Fund (Managed Fund)'},
            'EIGA.AX': {'region': 'AUSTRALIA', 'subcategory': 'Yield', 'benchmark': 'S&P/ASX 300 Franking Credit Adjusted Total Return Index (Tax-Exempt)', 'type': 'dividend', 'name': 'Perennial Income Generator Fund'},
            'IMLC.AX': {'region': 'AUSTRALIA', 'subcategory': 'Yield', 'benchmark': 'S&P/ASX 300 Accumulation Index', 'type': 'dividend', 'name': 'IML Concentrated Australian Share Fund (Quoted Managed Fund)'},
            'INIF.AX': {'region': 'AUSTRALIA', 'subcategory': 'Yield', 'benchmark': 'N/A', 'type': 'dividend', 'name': 'Intelligent Investor Australian Equity Income ETF'},
            'IHD.AX': {'region': 'AUSTRALIA', 'subcategory': 'Yield', 'benchmark': 'S&P/ASX Dividend Opportunities Accumulation', 'type': 'dividend', 'name': 'iShares S&P/ASX Dividend Opportunities ESG Screened ETF'},
            'RARI.AX': {'region': 'AUSTRALIA', 'subcategory': 'Yield', 'benchmark': 'Russell Australia ESG High Dividend', 'type': 'dividend', 'name': 'Russell Investments Australian Responsible Investment ETF'},
            'RDV.AX': {'region': 'AUSTRALIA', 'subcategory': 'Yield', 'benchmark': 'Russell Australia High Dividend', 'type': 'dividend', 'name': 'Russell Investments High Dividend Australian Shares ETF'},
            'AYLD.AX': {'region': 'AUSTRALIA', 'subcategory': 'Yield', 'benchmark': 'S&P/ASX BuyWrite Index', 'type': 'dividend', 'name': 'Global X S&P/ASX 200 Covered Call ETF'},
            'ZYAU.AX': {'region': 'AUSTRALIA', 'subcategory': 'Yield', 'benchmark': 'S&P/ASX 300 Shareholder Yield', 'type': 'dividend', 'name': 'Global X S&P/ASX 200 High Dividend ETF'},
            'SYI.AX': {'region': 'AUSTRALIA', 'subcategory': 'Yield', 'benchmark': 'MSCI Australia Select High Dividend Yield', 'type': 'dividend', 'name': 'SPDR MSCI Australia Select High Dividend Yield ETF'},
            'DVDY.AX': {'region': 'AUSTRALIA', 'subcategory': 'Yield', 'benchmark': 'Morningstar® Australia Dividend Yield Focus', 'type': 'dividend', 'name': 'VanEck Morningstar Australian Moat Income ETF'},
            'VHY.AX': {'region': 'AUSTRALIA', 'subcategory': 'Yield', 'benchmark': 'FTSE ASFA Australia High Dividend Yield', 'type': 'dividend', 'name': 'Vanguard Australian Shares High Yield ETF'},
            'MVA.AX': {'region': 'AUSTRALIA', 'subcategory': 'Property', 'benchmark': 'MVIS Australia A-REITs', 'type': 'sector', 'name': 'VanEck Australian Property ETF'},
            'VAP.AX': {'region': 'AUSTRALIA', 'subcategory': 'Property', 'benchmark': 'S&P/ASX 300 A-REIT', 'type': 'sector', 'name': 'Vanguard Australian Property Securities Index ETF'},
            'XARO.AX': {'region': 'AUSTRALIA', 'subcategory': 'Cash / Bonds', 'benchmark': 'RBA Inflation rate (Consumer Price Index)', 'type': 'bond', 'name': 'Ardea Real Outcome Bond Complex ETF'},
            'MMKT.AX': {'region': 'AUSTRALIA', 'subcategory': 'Cash / Bonds', 'benchmark': 'N/A', 'type': 'bond', 'name': 'Betashares Australian Cash Plus Active ETF'},
            'AGVT.AX': {'region': 'AUSTRALIA', 'subcategory': 'Cash / Bonds', 'benchmark': 'Solactive Australian Government 7 - 12 Year AUD TR', 'type': 'bond', 'name': 'BetaShares Australian Government Bond ETF'},
            'QPON.AX': {'region': 'AUSTRALIA', 'subcategory': 'Cash / Bonds', 'benchmark': 'Solactive Australian Bank Senior Floating Rate Bond', 'type': 'bond', 'name': 'BetaShares Australian Bank Senior Floating Rate Bond ETF'},
            'OZBD.AX': {'region': 'AUSTRALIA', 'subcategory': 'Cash / Bonds', 'benchmark': 'Bloomberg Australian Enhanced Yield Composite Bond Index', 'type': 'bond', 'name': 'BetaShares Australian Composite Bond ETF'},
            'AAA.AX': {'region': 'AUSTRALIA', 'subcategory': 'Cash / Bonds', 'benchmark': '30 day Bank Bill Swap Rate', 'type': 'bond', 'name': 'BetaShares Australian High Interest Cash ETF'},
            'CRED.AX': {'region': 'AUSTRALIA', 'subcategory': 'Cash / Bonds', 'benchmark': 'Solactive Australian Investment Grade Corporate Bond Select TR', 'type': 'bond', 'name': 'BetaShares Australian Investment Grade Corporate Bond ETF'},
            'BSUB.AX': {'region': 'AUSTRALIA', 'subcategory': 'Cash / Bonds', 'benchmark': 'Solactive Australian Major Bank Subordinated FRN Index', 'type': 'bond', 'name': 'Betashares Australian Major Bank Subordinated Debt ETF'},
            'HCRD.AX': {'region': 'AUSTRALIA', 'subcategory': 'Cash / Bonds', 'benchmark': 'Solactive Australian Investment Grade Corporate Bond Select DH Index', 'type': 'bond', 'name': 'BetaShares Interest Rate Hedged Australian Investment Grade Corporate Bond ETF'},
            'BNDS.AX': {'region': 'AUSTRALIA', 'subcategory': 'Cash / Bonds', 'benchmark': 'N/A', 'type': 'bond', 'name': 'BetaShares Western Asset Australian Bond Active ETF'},
            'AUDS.AX': {'region': 'AUSTRALIA', 'subcategory': 'Cash / Bonds', 'benchmark': 'Australian Dollar (AUD)', 'type': 'bond', 'name': 'Betashares Strong Australian Dollar Complex ETF'},
            'GGAB.AX': {'region': 'AUSTRALIA', 'subcategory': 'Cash / Bonds', 'benchmark': 'N/A', 'type': 'bond', 'name': 'Betashares Geared Long Australian Government Bond Complex ETF'},
            'GGFD.AX': {'region': 'AUSTRALIA', 'subcategory': 'Cash / Bonds', 'benchmark': 'N/A', 'type': 'bond', 'name': 'Betashares Geared Long US Treasury Bond Currency Hedged Complex ETF'},
            'ALTB.AX': {'region': 'AUSTRALIA', 'subcategory': 'Cash / Bonds', 'benchmark': 'Bloomberg Ausbond Govt 15+ Yr Index', 'type': 'bond', 'name': 'iShares 15+ Year Australian Government Bond ETF'},
            'BILL.AX': {'region': 'AUSTRALIA', 'subcategory': 'Cash / Bonds', 'benchmark': 'S&P/ASX Bank Bill Index', 'type': 'bond', 'name': 'iShares Core Cash ETF'},
            'IAF.AX': {'region': 'AUSTRALIA', 'subcategory': 'Cash / Bonds', 'benchmark': 'Bloomberg AusBond Composite 0+ Yr', 'type': 'bond', 'name': 'iShares Core Composite Bond ETF'},
            'ICOR.AX': {'region': 'AUSTRALIA', 'subcategory': 'Cash / Bonds', 'benchmark': 'Bloomberg AusBond Credit 0+ Yr', 'type': 'bond', 'name': 'iShares Core Corporate Bond ETF'},
            'ISEC.AX': {'region': 'AUSTRALIA', 'subcategory': 'Cash / Bonds', 'benchmark': 'S&P/ASX Bank Bill Index', 'type': 'bond', 'name': 'iShares Enhanced Cash ETF'},
            'ILB.AX': {'region': 'AUSTRALIA', 'subcategory': 'Cash / Bonds', 'benchmark': 'Bloomberg AusBond Inflation Government', 'type': 'bond', 'name': 'iShares Government Inflation ETF'},
            'IGB.AX': {'region': 'AUSTRALIA', 'subcategory': 'Cash / Bonds', 'benchmark': 'Bloomberg AusBond Treasury 0+ Yr', 'type': 'bond', 'name': 'iShares Treasury ETF'},
            'IYLD.AX': {'region': 'AUSTRALIA', 'subcategory': 'Cash / Bonds', 'benchmark': 'Bloomberg AusBond Credit and FRN Ex Big 4 Banks Index', 'type': 'bond', 'name': 'iShares Yield Plus ETF'},
            'MQIO.AX': {'region': 'AUSTRALIA', 'subcategory': 'Cash / Bonds', 'benchmark': 'Bloomberg AusBond Bank Bill Index', 'type': 'bond', 'name': 'Macquarie Income Opportunities Active ETF'},
            'RGB.AX': {'region': 'AUSTRALIA', 'subcategory': 'Cash / Bonds', 'benchmark': 'DBIQ 5-10 year Australian Government Bond', 'type': 'bond', 'name': 'Russell Investments Australian Government Bond ETF'},
            'RSM.AX': {'region': 'AUSTRALIA', 'subcategory': 'Cash / Bonds', 'benchmark': 'DBIQ 0-5 year Australian Semi-Government Bond', 'type': 'bond', 'name': 'Russell Investments Australian Semi-Government Bond ETF'},
            'RCB.AX': {'region': 'AUSTRALIA', 'subcategory': 'Cash / Bonds', 'benchmark': 'DBIQ 0-4 year Investment Grade Australian Corporate Bond', 'type': 'bond', 'name': 'Russell Investments Australian Select Corporate Bond ETF'},
            'BOND.AX': {'region': 'AUSTRALIA', 'subcategory': 'Cash / Bonds', 'benchmark': 'S&P/ASX Australian Fixed Interest', 'type': 'bond', 'name': 'SPDR S&P/ASX iBoxx Australian Bond ETF'},
            'GOVT.AX': {'region': 'AUSTRALIA', 'subcategory': 'Cash / Bonds', 'benchmark': 'S&P/ASX Government Bond', 'type': 'bond', 'name': 'SPDR S&P/ASX iBoxx Australian Government Bond ETF'},
            'XGOV.AX': {'region': 'AUSTRALIA', 'subcategory': 'Cash / Bonds', 'benchmark': 'S&P/ASX Government Bond 10-20 Year Index (SPBDG12T Index)', 'type': 'bond', 'name': 'VanEck 10+ Year Australian Government Bond ETF'},
            '1GOV.AX': {'region': 'AUSTRALIA', 'subcategory': 'Cash / Bonds', 'benchmark': 'S&P/ASX Government Bond 1-5 Year Index', 'type': 'bond', 'name': 'VanEck 1-5 Year Australian Government Bond ETF'},
            '5GOV.AX': {'region': 'AUSTRALIA', 'subcategory': 'Cash / Bonds', 'benchmark': 'S&P/ASX Government Bond 5-10 Year Index', 'type': 'bond', 'name': 'VanEck 5-10 Year Australian Government Bond ETF'},
            'PLUS.AX': {'region': 'AUSTRALIA', 'subcategory': 'Cash / Bonds', 'benchmark': 'Markit iBoxx AUD Corporates Yield Plus Index', 'type': 'bond', 'name': 'VanEck Australian Corporate Bond Plus ETF'},
            'FLOT.AX': {'region': 'AUSTRALIA', 'subcategory': 'Cash / Bonds', 'benchmark': 'Bloomberg AusBond Credit FRN 0+ Yr', 'type': 'bond', 'name': 'VanEck Australian Floating Rate ETF'},
            'SUBD.AX': {'region': 'AUSTRALIA', 'subcategory': 'Cash / Bonds', 'benchmark': 'iBoxx AUD Investment Grade Subordinated Debt Mid Price', 'type': 'bond', 'name': 'VanEck Australian Subordinated Debt ETF'},
            'VACF.AX': {'region': 'AUSTRALIA', 'subcategory': 'Cash / Bonds', 'benchmark': 'S&P/ASX Government Bond', 'type': 'bond', 'name': 'Vanguard Australian Corporate Fixed Interest Index ETF'},
            'VAF.AX': {'region': 'AUSTRALIA', 'subcategory': 'Cash / Bonds', 'benchmark': 'Bloomberg AusBond Credit 0+ Yr', 'type': 'bond', 'name': 'Vanguard Australian Fixed Interest Index ETF'},
            'VGB.AX': {'region': 'AUSTRALIA', 'subcategory': 'Cash / Bonds', 'benchmark': 'Bloomberg AusBond Govt 0+ Yr', 'type': 'bond', 'name': 'Vanguard Australian Government Bond Index ETF'},
            'BEAR.AX': {'region': 'AUSTRALIA', 'subcategory': 'Bear Market', 'benchmark': 'Negative Correlation to S&P/ASX 200', 'type': 'bear', 'name': 'BetaShares Australian Equities Bear Hedge Fund'},
            'BBOZ.AX': {'region': 'AUSTRALIA', 'subcategory': 'Bear Market', 'benchmark': 'Negative Correlation to S&P/ASX 20', 'type': 'bear', 'name': 'Betashares Australian Equities Strong Bear Complex ETF'},
            'ASAO.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'Asia Broad Exposure', 'benchmark': 'MSCI All Countries Asia Accumulation Index (ex Japan) (AUD unhedged)', 'type': 'broad_market', 'name': 'abrdn Sustainable Asian Opportunities Fund Active ETF (Managed Fund) Class E'},
            'QUS.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'US Broad Exposure', 'benchmark': 'FTSE RAFI U.S. 1000', 'type': 'broad_market', 'name': 'BetaShares S&P 500 Equal Weight ETF'},
            'GGUS.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'US Broad Exposure', 'benchmark': 'N/A', 'type': 'growth', 'name': 'Betashares Geared US Equities Currency Hedged Complex ETF'},
            'PAVE.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'US Broad Exposure', 'benchmark': 'Indxx U.S. Infrastructure Development Index', 'type': 'sector', 'name': 'Global X US Infrastructure Development ETF'},
            'MHOT.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'US Broad Exposure', 'benchmark': 'Morningstar Wide Moat Focus AUD Hedged Index', 'type': 'broad_market', 'name': 'VanEck Morningstar Wide Moat (AUD Hedged) ETF'},
            'MOAT.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'US Broad Exposure', 'benchmark': 'Morningstar® Wide Moat Focus', 'type': 'broad_market', 'name': 'VanEck Morningstar Wide Moat ETF'},
            'VTS.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'US Broad Exposure', 'benchmark': 'CRSP US Total Market', 'type': 'broad_market', 'name': 'Vanguard US Total Market Shares Index ETF'},
            'IVV.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'US S&P 500', 'benchmark': 'S&P 500', 'type': 'broad_market', 'name': 'iShares S&P 500 ETF'},
            'IHVV.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'US S&P 500', 'benchmark': 'S&P 500', 'type': 'broad_market', 'name': 'iShares S&P 500 AUD Hedged ETF'},
            'JEPI.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'US S&P 500', 'benchmark': "Standard & Poor's 500 Total Return Index", 'type': 'dividend', 'name': 'JPMorgan Equity Premium Income Active ETF'},
            'JHPI.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'US S&P 500', 'benchmark': "Standard & Poor's 500 Index", 'type': 'dividend', 'name': 'JPMorgan Equity Premium Income (Hedged) Active ETF'},
            'UYLD.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'US S&P 500', 'benchmark': 'Cboe S&P 500 BuyWrite Index', 'type': 'dividend', 'name': 'Global X S&P 500 Covered Call ETF'},
            'ZYUS.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'US S&P 500', 'benchmark': 'S&P 500 Low Volatility High Dividend Index', 'type': 'dividend', 'name': 'Global X S&P 500 High Yield Low Volatility ETF'},
            'SPY.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'US S&P 500', 'benchmark': 'S&P 500', 'type': 'broad_market', 'name': 'SPDR S&P 500 ETF'},
            'NDQ.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'US NASDAQ', 'benchmark': 'NASDAQ-100', 'type': 'growth', 'name': 'BetaShares NASDAQ 100 ETF'},
            'HNDQ.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'US NASDAQ', 'benchmark': 'NASDAQ-100', 'type': 'growth', 'name': 'Betashares Nasdaq 100 Currency Hedged ETF'},
            'QMAX.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'US NASDAQ', 'benchmark': 'N/A', 'type': 'dividend', 'name': 'Betashares Nasdaq 100 Yield Maximiser Complex ETF'},
            'LNAS.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'US NASDAQ', 'benchmark': 'NASDAQ-100', 'type': 'growth', 'name': 'Global X Ultra Long Nasdaq 100 Complex ETF'},
            'N100.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'US NASDAQ', 'benchmark': 'Global X US 100 Index', 'type': 'growth', 'name': 'Global X US 100 ETF'},
            'JPEQ.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'US NASDAQ', 'benchmark': 'Nasdaq-100 Index', 'type': 'dividend', 'name': 'JPMorgan US 100Q Equity Premium Income Active ETF'},
            'JPHQ.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'US NASDAQ', 'benchmark': 'Nasdaq-100 Index', 'type': 'dividend', 'name': 'JPMorgan US 100Q Equity Premium Income (Hedged) Active ETF'},
            'IJH.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'US Mid-Caps', 'benchmark': 'S&P Mid-Cap 400', 'type': 'growth', 'name': 'iShares S&P Mid-Cap ETF'},
            'IJR.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'US Small Caps', 'benchmark': 'S&P Small-Cap 600', 'type': 'growth', 'name': 'iShares S&P Small-Cap ETF'},
            'UTIP.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'US Yield', 'benchmark': 'Bloomberg Global Inflation-Linked: U.S. TIPS Total Return Index Hedged AUD', 'type': 'bond', 'name': 'Betashares Inflation-Protected U.S. Treasury Bond Currency Hedged ETF'},
            'UMAX.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'US Yield', 'benchmark': 'S&P 500', 'type': 'dividend', 'name': 'Betashares S&P 500 Yield Maximiser Complex ETF'},
            'IUSG.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'US Yield', 'benchmark': 'ICE U.S. Treasury Core Bond AUD Hedged Index', 'type': 'bond', 'name': 'iShares U.S. Treasury Bond (AUD Hedged) ETF'},
            'TBIL.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'US Yield', 'benchmark': 'Bloomberg U.S. Treasury Bills: 1-3 Months Unhedged AUD Index', 'type': 'bond', 'name': 'VanEck 1-3 Month US Treasury Bond ETF'},
            'BBUS.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'US Bear Market', 'benchmark': 'Negative correlation to S&P 500', 'type': 'bear', 'name': 'Betashares US Equities Strong Bear Currency Hedged Complex ETF'},
            'SNAS.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'US Bear Market', 'benchmark': 'Negative correlation to NASDAQ 100', 'type': 'bear', 'name': 'Global X Ultra Short Nasdaq100 Complex ETF'},
            'HEUR.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'Europe Broad Exposure', 'benchmark': 'WisdomTree Europe Hedged Equity', 'type': 'broad_market', 'name': 'Betashares Europe Currency Hedged ETF'},
            'ESTX.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'Europe Broad Exposure', 'benchmark': 'EURO STOXX 50', 'type': 'broad_market', 'name': 'Global X EURO STOXX 50 ETF'},
            'H100.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'Europe Broad Exposure', 'benchmark': 'AUD currency hedged FTSE 100 Index (before fees and expenses)', 'type': 'broad_market', 'name': 'Betashares FTSE 100 Currency Hedged ETF'},
            'IEU.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'Europe Broad Exposure', 'benchmark': 'S&P Europe 350', 'type': 'broad_market', 'name': 'iShares Europe ETF (AU)'},
            'VEQ.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'Europe Broad Exposure', 'benchmark': 'FTSE Developed Europe All Cap', 'type': 'broad_market', 'name': 'Vanguard FTSE Europe Shares ETF'},
            'EAFZ.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'Asia Broad Exposure', 'benchmark': 'MSCI Asia Ex Japan (non-accumulation (AUD) Index', 'type': 'growth', 'name': 'Ellerston Asia Growth Fund Complex ETF'},
            'FASI.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'Asia Broad Exposure', 'benchmark': 'MSCI All Country Asia ex-Japan Index NR', 'type': 'broad_market', 'name': 'Fidelity Asia Active ETF'},
            'IAA.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'Asia Broad Exposure', 'benchmark': 'S&P Asia 50', 'type': 'broad_market', 'name': 'iShares Asia 50 ETF (AU)'},
            'PAXX.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'Asia Broad Exposure', 'benchmark': 'N/A', 'type': 'broad_market', 'name': 'Platinum Asia Fund (Quoted Managed Hedge Fund)'},
            'VAE.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'Asia Broad Exposure', 'benchmark': 'FTSE Asia Pacific ex-Japan, Aust. & NZ', 'type': 'broad_market', 'name': 'Vanguard FTSE Asia ex Japan Shares Index ETF'},
            'IIND.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'Asia Individual Countries', 'benchmark': 'Solactive India Quality Select Index', 'type': 'broad_market', 'name': 'BetaShares India Quality ETF'},
            'HJPN.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'Asia Individual Countries', 'benchmark': 'WisdomTree Japan Hedged Equity', 'type': 'broad_market', 'name': 'Betashares Japan Currency Hedged ETF'},
            'NDIA.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'Asia Individual Countries', 'benchmark': 'NSE Nifty50', 'type': 'broad_market', 'name': 'Global X India Nifty 50 ETF'},
            'FIIN.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'Asia Individual Countries', 'benchmark': 'MSCI India Index NR', 'type': 'broad_market', 'name': 'Fidelity India Active ETF'},
            'IZZ.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'Asia Individual Countries', 'benchmark': 'FTSE China 50', 'type': 'broad_market', 'name': 'iShares China Large-Cap ETF (AU)'},
            'IJP.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'Asia Individual Countries', 'benchmark': 'MSCI Japan', 'type': 'broad_market', 'name': 'iShares MSCI Japan ETF (AU)'},
            'IKO.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'Asia Individual Countries', 'benchmark': 'MSCI Korea 25/50', 'type': 'broad_market', 'name': 'iShares MSCI South Korea ETF (AU)'},
            'CETF.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'Asia Individual Countries', 'benchmark': 'FTSE China A50', 'type': 'broad_market', 'name': 'VanEck FTSE China A50 ETF'},
            'XMET.AX': {'region': 'COMMODITIES', 'subcategory': 'Broad Exposure', 'benchmark': 'Nasdaq Sprott Energy Transition Materials Select Index', 'type': 'commodity', 'name': 'BetaShares Energy Transition Metals ETF'},
            'BCOM.AX': {'region': 'COMMODITIES', 'subcategory': 'Broad Exposure', 'benchmark': 'Bloomberg Commodity Index Excess Return 3 Month Forward', 'type': 'commodity', 'name': 'Global X Bloomberg Commodity Complex ETF'},
            'ETPMPM.AX': {'region': 'COMMODITIES', 'subcategory': 'Broad Exposure', 'benchmark': 'N/A', 'type': 'commodity', 'name': 'Global X Physical Precious Metals Basket Structured'},
            'QAU.AX': {'region': 'COMMODITIES', 'subcategory': 'Gold', 'benchmark': 'Physical Gold', 'type': 'commodity', 'name': 'Betashares Gold Bullion Currency Hedged ETF'},
            'GOLD.AX': {'region': 'COMMODITIES', 'subcategory': 'Gold', 'benchmark': 'Physical Gold', 'type': 'commodity', 'name': 'Global X Physical Gold Structured'},
            'MNRS.AX': {'region': 'COMMODITIES', 'subcategory': 'Gold', 'benchmark': 'Nasdaq Global ex-Australia Gold Miners Hedged', 'type': 'commodity', 'name': 'Betashares Global Gold Miners Currency Hedged ETF'},
            'GXLD.AX': {'region': 'COMMODITIES', 'subcategory': 'Gold', 'benchmark': 'Solactive Gold Spot London Close Index', 'type': 'commodity', 'name': 'Global X Gold Bullion ETF'},
            'GLDN.AX': {'region': 'COMMODITIES', 'subcategory': 'Gold', 'benchmark': 'LMBA Gold Price PM AUD Index', 'type': 'commodity', 'name': 'iShares Physical Gold ETF'},
            'PMGOLD.AX': {'region': 'COMMODITIES', 'subcategory': 'Gold', 'benchmark': 'Physical Gold', 'type': 'commodity', 'name': 'Perth Mint Gold Structured Product'},
            'NUGG.AX': {'region': 'COMMODITIES', 'subcategory': 'Gold', 'benchmark': 'Australian Sourced Gold', 'type': 'commodity', 'name': 'VanEck Gold Bullion ETF'},
            'GDX.AX': {'region': 'COMMODITIES', 'subcategory': 'Gold', 'benchmark': 'NYSE Arca Gold Miners', 'type': 'commodity', 'name': 'VanEck Gold Miners ETF'},
            'ETPMAG.AX': {'region': 'COMMODITIES', 'subcategory': 'Silver', 'benchmark': 'Physical Silver', 'type': 'commodity', 'name': 'Global X Physical Silver Structured'},
            'ETPMPT.AX': {'region': 'COMMODITIES', 'subcategory': 'Platinum', 'benchmark': 'Physical Platinum', 'type': 'commodity', 'name': 'Global X Physical Platinum Structured'},
            'ETPMPD.AX': {'region': 'COMMODITIES', 'subcategory': 'Pallidium', 'benchmark': 'Physical Palladium', 'type': 'commodity', 'name': 'Global X Physical Palladium Structured'},
            'OOO.AX': {'region': 'COMMODITIES', 'subcategory': 'Energy', 'benchmark': 'S&P GSCI Crude Oil', 'type': 'commodity', 'name': 'Betashares Crude Oil Index Currency Hedged Complex ETF'},
            'FOOD.AX': {'region': 'COMMODITIES', 'subcategory': 'Agriculture', 'benchmark': 'Nasdaq Global ex-Australia Agriculture Companies Hedged', 'type': 'commodity', 'name': 'Betashares Global Agriculture Companies Currency Hedged ETF'},
            '28BB.AX': {'region': 'AUSTRALIA', 'subcategory': 'Cash / Bonds', 'benchmark': 'Bloomberg AusBond Bank Bill Index', 'type': 'bond', 'name': 'Betashares 2028 Fixed Term Corporate Bond Active ETF'},
            '29BB.AX': {'region': 'AUSTRALIA', 'subcategory': 'Cash / Bonds', 'benchmark': 'Bloomberg AusBond Bank Bill Index', 'type': 'bond', 'name': 'Betashares 2029 Fixed Term Corporate Bond Active ETF'},
            '30BB.AX': {'region': 'AUSTRALIA', 'subcategory': 'Cash / Bonds', 'benchmark': 'Bloomberg AusBond Bank Bill Index', 'type': 'bond', 'name': 'Betashares 2030 Fixed Term Corporate Bond Active ETF'},
            'A300.AX': {'region': 'AUSTRALIA', 'subcategory': 'Index Tracking', 'benchmark': 'S&P/ASX 300', 'type': 'broad_market', 'name': 'Global X Australia 300 ETF'},
            'AEBD.AX': {'region': 'GLOBAL', 'subcategory': 'Emerging Markets', 'benchmark': 'J.P. Morgan EMBI Global Core Index (AUD Hedged)', 'type': 'bond', 'name': 'Betashares Ethical Australian Composite Bond ETF'},
            'AINF.AX': {'region': 'AUSTRALIA', 'subcategory': 'Sectors', 'benchmark': 'S&P/ASX 200 A-REIT', 'type': 'sector', 'name': 'Global X Artificial Intelligence Infrastructure ETF'},
            'ALFA.AX': {'region': 'AUSTRALIA', 'subcategory': 'Broad Exposure', 'benchmark': 'N/A', 'type': 'broad_market', 'name': 'VanEck Australian Long Short Complex ETF'},
            'ALPH.AX': {'region': 'AUSTRALIA', 'subcategory': 'Broad Exposure', 'benchmark': 'N/A', 'type': 'broad_market', 'name': 'Schroder Global Equity Alpha Fund – Active ETF'},
            'ARMR.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'N/A', 'type': 'sector', 'name': 'Betashares Global Defence ETF'},
            'BANK.AX': {'region': 'AUSTRALIA', 'subcategory': 'Sectors', 'benchmark': 'S&P/ASX 200 Financials', 'type': 'sector', 'name': 'Global X Australian Bank Credit ETF'},
            'BTXX.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'N/A', 'type': 'crypto', 'name': 'DigitalX Bitcoin ETF'},
            'CIIH.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'Asia Individual Countries', 'benchmark': 'MSCI China Index', 'type': 'broad_market', 'name': 'CBIIHETF ETF UNITS [CIIH]'},
            'CIVH.AX': {'region': 'US / EUROPE / ASIA', 'subcategory': 'Asia Individual Countries', 'benchmark': 'MSCI China Index (Hedged AUD)', 'type': 'broad_market', 'name': 'ClearBridge Global Infrastructure Value Fund (Hedged) Active ETF'},
            'CORE.AX': {'region': 'AUSTRALIA', 'subcategory': 'Broad Exposure', 'benchmark': 'S&P/ASX 200 Accumulation Index', 'type': 'broad_market', 'name': 'Schroder Global Core Fund Active ETF'},
            'CUIV.AX': {'region': 'COMMODITIES', 'subcategory': 'Broad Exposure', 'benchmark': 'N/A', 'type': 'commodity', 'name': 'ClearBridge Global Infrastructure Value Fund Active ETF'},
            'DAVA.AX': {'region': 'AUSTRALIA', 'subcategory': 'Broad Exposure', 'benchmark': 'N/A', 'type': 'broad_market', 'name': 'Dimensional Australian Value Active ETF'},
            'DCOR.AX': {'region': 'AUSTRALIA', 'subcategory': 'Broad Exposure', 'benchmark': 'S&P/ASX 200 Accumulation Index', 'type': 'broad_market', 'name': 'Einvest Core Income Fund - Chi-X - Trading Managed Fund'},
            'DFND.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'N/A', 'type': 'sector', 'name': 'VanEck Global Defence ETF'},
            'DGSM.AX': {'region': 'AUSTRALIA', 'subcategory': 'Small Cap', 'benchmark': 'S&P/ASX Small Ordinaries', 'type': 'growth', 'name': 'Dimensional Global Small Company Active ETF'},
            'DGVA.AX': {'region': 'AUSTRALIA', 'subcategory': 'Broad Exposure', 'benchmark': 'N/A', 'type': 'broad_market', 'name': 'Dimensional Global Value Active ETF'},
            'DIFF.AX': {'region': 'AUSTRALIA', 'subcategory': 'Broad Exposure', 'benchmark': 'N/A', 'type': 'broad_market', 'name': 'Perpetual Diversified Income Active ETF'},
            'DRGN.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'N/A', 'type': 'sector', 'name': 'Global X China Tech ETF'},
            'DTEC.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'N/A', 'type': 'growth', 'name': 'Global X Defence Tech ETF'},
            'EQIN.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'N/A', 'type': 'broad_market', 'name': 'Investors Mutual Equity Income - Complex ETF'},
            'FHNG.AX': {'region': 'AUSTRALIA', 'subcategory': 'Sectors', 'benchmark': 'S&P/ASX 200 Financials', 'type': 'sector', 'name': 'Global X FANG+ (Currency Hedged) ETF'},
            'FSML.AX': {'region': 'AUSTRALIA', 'subcategory': 'Small Cap', 'benchmark': 'S&P/ASX Small Ordinaries', 'type': 'growth', 'name': 'Firetrail Australian Small Companies Fund - Active ETF'},
            'GARP.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'N/A', 'type': 'growth', 'name': 'Global X S&P World ex Australia GARP ETF'},
            'GCQF.AX': {'region': 'GLOBAL', 'subcategory': 'Broad Exposure', 'benchmark': 'N/A', 'type': 'broad_market', 'name': 'GCQ Global Equities Complex ETF'},
            'GHLD.AX': {'region': 'COMMODITIES', 'subcategory': 'Gold', 'benchmark': 'Physical Gold', 'type': 'commodity', 'name': 'Global X Gold Bullion (Currency Hedged) ETF'},
            'GRIN.AX': {'region': 'GLOBAL', 'subcategory': 'Sectors', 'benchmark': 'FTSE Developed Core Infrastructure 50/50', 'type': 'sector', 'name': 'VanEck India Growth Leaders ETF'}
        }
        
        print(f"ETF Database loaded: {len(self.etf_data)} ETFs (with names)")
    
    def get_etf_name(self, ticker: str) -> str:
        """
        Get ETF name from integrated database
        
        Args:
            ticker: ETF ticker symbol
            
        Returns:
            ETF name or ticker if not found
        """
        if ticker in self.etf_data:
            return self.etf_data[ticker].get('name', ticker)
        return ticker
    
    def get_etf_info_with_name(self, ticker: str) -> dict:
        """
        Get complete ETF information including name
        
        Args:
            ticker: ETF ticker symbol
            
        Returns:
            Complete ETF info with name included
        """
        return self.etf_data.get(ticker, {})
    
    def search_etfs_by_name(self, search_term: str) -> list:
        """
        Search ETFs by name
        
        Args:
            search_term: Term to search for in ETF names
            
        Returns:
            List of matching ETFs with ticker and name
        """
        results = []
        search_lower = search_term.lower()
        
        for ticker, info in self.etf_data.items():
            name = info.get('name', '').lower()
            if search_lower in name:
                results.append({
                    'ticker': ticker,
                    'name': info.get('name', ''),
                    'region': info.get('region', ''),
                    'type': info.get('type', '')
                })
        
        return results
    
    